spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ################################
  # Spring Boot Auto Configuration
  ################################

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  #############################
  # DataSource Configuration
  #############################

  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:postgresql://10.0.1.91:5432/test
      username: test
      password: Dd98969321$9
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      connection-test-query: SELECT 1
      maximum-pool-size: 3

#############################
# Logging Configuration
#############################

logging:
  config: classpath:/logback.xml
